"""Semantic signal: LLM-based analysis of context, tone, and semantics.

Sends the raw text to the Groq API (llama-3.3-70b-versatile) and asks the model
to classify how likely the text is AI-generated on a 0.0-1.0 scale, where 0.0 is
confidently human and 1.0 is confidently AI.

The function is async so it can run concurrently with the local structural signal
(see planning.md, "Multi-Signal Detection Pipeline").
"""

import json
import os

from groq import AsyncGroq

MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = (
    "You are a forensic text-attribution analyst. You judge whether a passage was "
    "written by a human or generated by an AI language model, based on context, "
    "tone, and semantics. Robotic, uniform, emotionally flat prose leans AI; "
    "idiosyncratic, uneven, personal prose leans human. Be aware that skilled "
    "expert human writing can also look clean and uniform.\n\n"
    "Respond with ONLY a JSON object, no prose, in this exact shape:\n"
    '{"score": <float 0.0-1.0>, "reasoning": "<one short sentence>"}\n'
    "where 0.0 = confidently human and 1.0 = confidently AI-generated."
)

# Lazily instantiated so importing this module never requires the API key.
_client: AsyncGroq | None = None


def _get_client() -> AsyncGroq:
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY is not set in the environment.")
        _client = AsyncGroq(api_key=api_key)
    return _client


async def analyze_semantic(text: str) -> float:
    """Return an AI-likelihood score in [0.0, 1.0] from the semantic signal.

    0.0 = confidently human, 1.0 = confidently AI.
    Raises on API/parse failure; the caller decides how to handle it.
    """
    client = _get_client()

    response = await client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        temperature=0.0,
        response_format={"type": "json_object"},
    )

    raw = response.choices[0].message.content
    payload = json.loads(raw)
    score = float(payload["score"])

    # Clamp to the valid range in case the model drifts outside it.
    return max(0.0, min(1.0, score))
